### PR TITLE
Feature/code refactor

### PR DESCRIPTION
**Pull request by ulisesedu7**
## Description
On this pull request, we've refactored our code to use better guidelines and improved the main file so that it only call for the options and gets the user interaction rather than having some logic.

**Task:** https://github.com/microverseinc/curriculum-ruby/blob/main/oop/school_library_refactor.md

This PR makes the following changes:
- Edit the main file to reduce the logic on it
- Create new classes to handle the logic of the app properly and reduce the code

## Type of change

- [X] Refactor (non-breaking change that neither fixes a bug nor adds a feature)

## Checklist

- [X] My code follows the style guidelines of this project (no linters errors)
- [X] I have checked my code and corrected any misspellings
- [X] I have commented on my code
- [X] I have deleted any unused code as comments in my codebase

### CODE REVIEW

**Review by BertrandConxy — CHANGES_REQUESTED** [review]
Hi Team ✋ , 

Good job so far! 👏 👏 
There are some issues that you still need to work on to go to the next project but you are almost there! 🏃‍♂️ 🏃‍♂️ 


## Highlights 💪 
- Project still works well
- No linter errors
- correct git-flow is used
- good PR


## Required Changes ♻️

- [x]  In the `utils folder` you have created a text file called `create_` which is of no use. It is the best practice to remove everything you don't need (YAGNI) so please remove it to make your codebase clean 😃 👍 

## Optional suggestions

- [x] [OPTIONAL] Your project works well but It would be much better if you have a good project structure. Some of the suggestions are to move all your module files to the `modules folder ` 😉 👍 

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ulisesedu7** [comment]
@BertrandConxy Thank you very much for the review! I'll just work on the changes and send it back.

**Comment by BertrandConxy** [comment]
You are welcome 👍👍

**Review by BertrandConxy — APPROVED** [review]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💪 

- No linter errors
- project requirements are met
- project works fine
- Best improvement based on reviewer's suggestions

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ulisesedu7** [comment]
@BertrandConxy Thanks!!

**Pull request merged**
