### PR TITLE
Add people feature

### PR DESCRIPTION
**Pull request by ulisesedu7**
## Description
This project creates the classes using OOP for a school library

**Task:** https://github.com/microverseinc/curriculum-ruby/blob/main/oop/school_library_people.md

This PR makes the following changes:
- Creates Person, Studen, and Teacher classes
- Creates methods for each class to check their age or permissions

## Type of change

- [X] New feature (non-breaking change which adds functionality)
- [X] Test (change related to testing)

## Checklist

- [X] My code follows the style guidelines of this project (no linters errors)
- [X] I have checked my code and corrected any misspellings
- [X] I have commented on my code
- [X] I have deleted any unused code as comments in my codebase

### CODE REVIEW

**Review by HAMMAS-SALEEM — COMMENTED** [review]
# Invalid Pull Request :red_circle: :traffic_light: :rotating_light:

## Hey @ulisesedu7 :wave: 

**You have made a great effort on your project :blush: and I can see that but unfortunately I can not proceed with a code review of your pull request due to the following reasons :receipt:**

## 1. 
- [x] You don't have a descriptive readme for your project. Kindly make your readme descriptive using [microverse template](https://github.com/microverseinc/readme-template/blob/master/README.md) :blush:
### Once you implement all the changes you should be ready to submit your project for a review :rocket: :rocket:

Cheers and Happy coding!👏👏👏

### Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @HAMMAS-SALEEM in your question so I can receive the notification. You can reach out to me on slack by searching my name (Hammas Bin Saleem) for any explanation.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ulisesedu7** [comment]
@HAMMAS-SALEEM Hey Hammas, thank you very much for pointing that out! I totally forgot... my bad, I apologize for that. I'll start fixing it right away and re-submit the project.

**Review by VICTOR-CHUKWU — APPROVED** [review]
Hi @ulisesedu7 , 
# STATUS: APPROVED! 🥇 💯 
done

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ulisesedu7** [comment]
@VICTOR-CHUKWU Thank you very much! Merging now!

**Pull request merged**
